### ISSUE TITLE
setup_requires docutils>=0.3

### ISSUE THREAD

**Issue by mfeurer** [sfalkner/pynisher#5]
setup.py contains the following line:

```
install_requires = ['docutils>=0.3', 'setuptools', 'psutil'],
```

According to the [docutils page](http://docutils.sourceforge.net/) 0.12 is the latest release. This can make the installation of packages which have the pynisher as a dependency fail.

**Comment by sfalkner** [comment]
Isn't 0.12 > 0.3? Does that actually fail somewhere?

**Comment by mfeurer** [comment]
Had this error:

```
  Could not find a version that satisfies the requirement docutils>=0.3 (from pynisher>=0.4.1->smac) (from versions: )
No matching distribution found for docutils>=0.3 (from pynisher>=0.4.1->smac)
```

Found the problem, it was in the call to pip.
